_app/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Contact;
use app\models\DownloadFile;
use Yii;
use yii\helpers\StringHelper;
use yii\web\Controller;
use yii\web\Response;

class SiteController extends Controller
{
    public $enableCsrfValidation = false;

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return string
     */
    public function actionTentang()
    {
        
        $model = new DownloadFile();
        
        if ($model->load($this->request->post())) {
            
            if ($model->save()) {
                return Yii::$app->getResponse()->sendFile(dirname(__DIR__) . '/donwloads/test.pdf', 'ComPro ARN');
            } else {
                Yii::$app->session->setFlash('error', 'Permintaan download file gagal. Mohon teliti kembali form Anda.');
            }
        }

        return $this->render('tentang', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     */
    public function actionProsesMaklon()
    {
        return $this->render('proses-maklon');
    }

    /**
     * @return string
     */
    public function actionSertifikasi()
    {
        return $this->render('sertifikasi');
    }

    /**
     * @return string
     */
    public function actionOem()
    {
        return $this->render('oem');
    }

    /**
     * @return string
     */
    public function actionOdm()
    {
        return $this->render('odm');
    }

    /**
     * @return string
     */
    public function actionKonsultasiProduk()
    {
        return $this->render('konsultasi-produk');
    }
    
    /**
     * @return string
     */
    public function actionResearchDevelopment()
    {
        return $this->render('research-development');
    }
    
    /**
     * @return string
     */
    public function actionMerekPaten()
    {
        return $this->render('merek-paten');
    }

    /**
     * @return string
     */
    public function actionFaq()
    {
        return $this->render('faq');
    }

    /**
     * @return string
     */
    public function actionProduk()
    {
        return $this->render('produk');
    }

    /**
     * @return string
     */
    public function actionBlog()
    {
        return $this->render('blog');
    }

    /**
     * @return string
     */
    public function actionFaqIzinBpom()
    {
        return $this->render('faq-izin-bpom');
    }
    public function actionFaqIzinHki()
    {
        return $this->render('faq-izin-hki');
    }
    public function actionFaqIzinHalal()
    {
        return $this->render('faq-izin-halal');
    }

    /**
     * @return string
     */
    public function actionKontakKami()
    {
        $model = new Contact();
        
        if ($model->load($this->request->post())) {
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Jadwal kunjungan berhasil dikirimkan.');

                return $this->refresh();
            } else {
                Yii::$app->session->setFlash('error', 'Jadwal kunjungan gagal dikirimkan. Mohon teliti kembali form Anda.');
            }
        }

        return $this->render('kontak-kami', [
            'model' => $model,
        ]);
    }
}

_app/views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;

?>

<div class="site-error m-5 text-center" style="min-height: 75vh; padding-top: 120px">

    <h1 class="mt-5 fw-bold"><?= Html::encode($this->title) ?></h1>

    <h4 class="my-4">
        <?= nl2br(Html::encode($message)) ?>
    </h4>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

_app/views/site/faq-izin-halal.php
<?php

/** @var yii\web\View $this */

use yii\helpers\FileHelper;
use yii\helpers\Html;

$this->title = 'Izin Halal Kosmetik';

?>


<!-- Start banner_about -->
<section class="pt_banner_inner banner_px_image">
    <div class="parallax_cover">
        <img class="cover-parallax h-100vh" src="<?= Yii::$app->homeUrl ?>web/maklon/header.jpg" alt="">
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <div class="banner_title_inner c-white">
                    <h1 data-aos="fade-up" data-aos-delay="0">
                        Izin Halal Kosmetik
                    </h1>
                    <p data-aos="fade-up" data-aos-delay="100" class="banner_title_inner c-yollow">
                        Maklon Nutrisi & Beauty - PT Alga Rosan Nusantara
                    </p>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- End banner_about -->

<section class="faq_one_inner py-0 mt-0 margin-b-6 w-100">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-lg-5">
                <div class="title_sections_inner margin-b-5">

                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <!-- block Collapse -->
                <div class="faq_section faq_demo3 faq_with_icon">
                    <div class="block_faq">
                        <div class="accordion" id="accordionExample">
                            <div class="card">
                                <div class="card-header " id="headingOne">
                                    <h3 class="mb-0">
                                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                            Sertifikat Halal
                                        </button>
                                    </h3>
                                </div>
                                <div id="collapseOne" class="collapse " aria-labelledby="headingOne" data-parent="#accordionExample">
                                    <div class="card-body">
                                        <p class="mb-0">Sertifikat Halal MUI adalah fatwa tertulis Majelis Ulama Indonesia yang
                                            menyatakan kehalalan suatu produk sesuai dengan syari’at Islam. Sertifikat
                                            Halal MUI ini merupakan syarat untuk mendapatkan ijin pencantuman label
                                            halal pada kemasan produk dari instansi pemerintah yang berwenang.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header" id="headingTwo">
                                    <h3 class="mb-0">
                                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                            Tujuan Sertifikasi Halal
                                        </button>
                                    </h3>
                                </div>
                                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                                    <div class="card-body">
                                        <p class="mb-0">Sertifikasi Halal MUI pada produk pangan, obat-obat, kosmetika dan produk
                                            lainnya dilakukan untuk memberikan kepastian status kehalalan, sehingga
                                            dapat menenteramkan batin konsumen dalam mengkonsumsinya.
                                            Kesinambungan proses produksi halal dijamin oleh produsen dengan cara
                                            menerapkan Sistem Jaminan Halal.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

_app/views/site/merek-paten.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Merek & Paten';

?>

<!-- Start banner_about -->
<section class="pt_banner_inner banner_px_image">
    <div class="parallax_cover">
        <img class="cover-parallax h-100vh" src="<?= Yii::$app->homeUrl ?>web/maklon/header.jpg" alt="">
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-6">
                <div class="banner_title_inner c-white">
                    <h1 data-aos="fade-up" data-aos-delay="0">
                        Merek & Paten
                    </h1>
                    <p data-aos="fade-up" data-aos-delay="100" class="banner_title_inner c-yollow">
                        Maklon Nutrisi & Beauty - PT Alga Rosan Nusantara
                    </p>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- End banner_about -->

<!-- Start Services -->
<section class="services_section padding-t-5">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-lg-12">
                <div class="title_sections_inner margin-b-5">
                    <h3>Tidak hanya produksi, kami juga membantu
                        Anda mengurus perizinan BPOM, Hak Paten,
                        dan Sertifikat Halal. Bantuan ini mempercepat
                        produk Anda masuk ke Pasar.
                    </h3>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-8 mb-4 mb-lg-0 margin-b-5">
                <div class="items_serv">
                    <div class="media">
                        <div>
                            <img src="<?= Yii::$app->homeUrl ?>web/maklon/sertifikat-bpom.png" alt="" style="width: 80%;" />
                        </div>
                        <div class="media-body">
                            <h3>IZIN BPOM KOSMETIK</h3>
                            <p>Jangan biarkan kosmetik anda menjadi produk
                                ilegal atau tidak terdaftar secara resmi. Tim
                                kami akan membantu anda dalam setiap proses
                                dan prosedur yang terlibat dalam memperoleh
                                izin BPOM Produk anda.
                            </p>
                            <br>
                            <a href="<?= Url::toRoute(['/site/faq-izin-bpom']) ?>" class="btn btn_md_primary sweep_top sweep_letter bg-green2 c-white rounded-8">
                                <div class="inside_item">
                                    <span data-hover="Pelajari Lebih Lanjut">Pelajari Lebih Lanjut</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-8 mb-4 mb-lg-0 margin-b-5">
                <div class="items_serv">
                    <div class="media">
                        <div>
                            <img src="<?= Yii::$app->homeUrl ?>web/maklon/hki-250x200.png" alt="" style="width: 80%;" />
                        </div>
                        <div class="media-body">
                            <h3>Izin HKI atau Paten Kosmetik</h3>
                            <p>Jangan sampai Brand anda ditiru orang lain,
                                Nose Herbalindo akan membantu anda untuk
                                pendaftaran merk, pendaftaran hak paten,
                                pendaftaran hak cipta dan pendaftaran lainnya.
                            </p>
                            <br>
                            <a href="<?= Url::toRoute(['/site/faq-izin-hki']) ?>" class="btn btn_md_primary sweep_top sweep_letter bg-green2 c-white rounded-8">
                                <div class="inside_item">
                                    <span data-hover="Pelajari Lebih Lanjut">Pelajari Lebih Lanjut</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-8 mb-4 mb-lg-0 margin-b-5">
                <div class="items_serv">
                    <div class="media">
                        <div>
                            <img src="<?= Yii::$app->homeUrl ?>web/maklon/sertifikat-mui.png" alt="" style="width: 80%;" />
                        </div>
                        <div class="media-body">
                            <h3>IZIN HALAL KOSMETIK</h3>
                            <p>Adanya sertifikat halal MUI ini, menjadikan
                                tingkat kepercayaan yang tinggi bagi
                                masyarakat bahwa produk ini memang benar-benar halal, khususnya kosmetik yang
                                digunakan dalam aktivitas sehari-hari.
                            </p>
                            <br>
                            <a href="<?= Url::toRoute(['/site/faq-izin-halal']) ?>" class="btn btn_md_primary sweep_top sweep_letter bg-green2 c-white rounded-8">
                                <div class="inside_item">
                                    <span data-hover="Pelajari Lebih Lanjut">Pelajari Lebih Lanjut</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

_app/views/site/odm.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'ODM - Maklon Nutrisi & Beauty';

?>

<!-- Start banner_about -->
<section class="pt_banner_inner banner_px_image">
    <div class="parallax_cover">
        <img class="cover-parallax h-100vh" src="<?= Yii::$app->homeUrl ?>web/maklon/header.jpg" alt="">
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-12">
                <div class="banner_title_inner c-white">
                    <h1 data-aos="fade-up" data-aos-delay="0">
                        ODM - Original Design Manufacture
                    </h1>
                    <p data-aos="fade-up" data-aos-delay="100" class="banner_title_inner c-yollow">
                        Maklon Nutrisi & Beauty - PT Alga Rosan Nusantara
                    </p>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- End banner_about -->

<section class="team_overlay_style team_default_style padding-t-10">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-8">
                <div class="item_group">
                    <div class="image_ps">
                        <img src="<?= Yii::$app->homeUrl ?>web/maklon/OEM.jpg" alt="">
                        <div class="content_txt left-side">
                            <h3>ODM</h3>
                            <p>Kami membantu anda membangun produk
                                nutrisi & beauty anda. Mulai dari konsep
                                produk, formula, R&D, produksi hingga
                                distribusinya (toko online).
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-6 col-lg-12">
                <div class="media-body">
                    <h3>Jasa Pembuatan Kosmetik ODM</h3>
                    <p>Merupakan sistem layanan total bagi kami yang bertanggung
                        jawab atas semua proses produksi mulai dari perencanaan
                        produk, pengembangan, produksi hingga manajemen kualitas
                        dan pengiriman berdasarkan teknologi, pengalaman dan
                        pengetahuan kami.</p>
                    <p>Jika anda ingin menciptakan desain dan spesifikasi produk
                        kosmetik yang anda inginkan secara keseluruhan dan memiliki
                        sumber daya yang terbatas dalam membangun dan membuat
                        desain, maka perusahaan ODM dapat membuat konsep yang
                        anda inginkan menjadi barang yang nyata dan laku dipasaran.</p>
                    <p>Apapun yang anda butuhkan dan harapkan untuk perusahaan
                        kosmetik anda, kami akan siap menangani R&D, konsep produk,
                        pengujian dan memanufakturkannya
                    </p>
                </div>
            </div>
        </div>
        <div class="row justify-content-center text-center">
            <div class="col-md-8 col-lg-12">
                <div class="title_sections">
                    <a href="<?= Url::toRoute(['/site/kontak-kami']) ?>" class="btn btn_md_primary margin-t-2 bg-green2 c-white sweep_top sweep_letter rounded-12">
                        <div class="inside_item">
                            <span data-hover="Buat Produk OEM">Buat Produk OEM</span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-lg-12">
                <div class="title_sections">
                    <h3>Free Jasa pembuatan Toko Online dengan sharing profit penjualan</h3>
                    <ul style="color: #6c7a87;">
                        <li>Hingga 100% Pembandingan yang Akurat</li>
                        <li>Memenuhi Kebutuhan dan Anggaran Anda</li>
                        <li>Stabilitas & Kompatibilitas Diuji</li>
                    </ul>
                </div>
            </div>

            <div class="col-md-8 col-lg-12">
                <div class="title_sections">
                    <!-- <div class="before_title">
                        <span class="c-green2">Integration</span>
                    </div> -->
                    <h3>Jasa pembuatan Toko Online tanpa sharing profit penjualan (beli putus)</h3>
                </div>
            </div>
        </div>
    </div>
</section>

_app/views/site/oem.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'OEM - Original Equipment Manufacture';

?>

<!-- Start banner_about -->
<section class="pt_banner_inner banner_px_image">
    <div class="parallax_cover">
        <img class="cover-parallax h-100vh" src="<?= Yii::$app->homeUrl ?>web/maklon/header.jpg" alt="">
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-12">
                <div class="banner_title_inner c-white">
                    <h1 data-aos="fade-up" data-aos-delay="0">
                        OEM - Original Equipment Manufacture
                    </h1>
                    <p data-aos="fade-up" data-aos-delay="100" class="banner_title_inner c-yollow">
                        Maklon Nutrisi & Beauty - PT Alga Rosan Nusantara
                    </p>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- End banner_about -->

<section class="team_overlay_style team_default_style padding-t-10">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-8">
                <div class="item_group">
                    <div class="image_ps">
                        <img src="<?= Yii::$app->homeUrl ?>web/maklon/OEM.jpg" alt="">
                        <div class="content_txt left-side">
                            <h3>OEM</h3>
                            <p>Kami membantu anda memproduksi produk
                                nutrisi & beauty sesuai dengan formula yang
                                anda miliki. Semua riset pasar, R&D serta
                                pengembangan produk tersebut dapat
                                dilakukan oleh anda sendiri.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-12">
                <div class="media-body">
                    <h3>Jasa Pembuatan Kosmetik OEM</h3>
                    <p>Merupakan perusahaan yang memproduksi kosmetik
                        berdasarkan desain dan spesifikasi yang anda inginkan. Anda
                        dapat melakukan semua riset pasar, R&D dan
                        mengembangkan produk anda sendiri dan kami akan
                        membantu untuk memanufaktur atau memproduksi produk
                        kosmetik yang sesuai dengan permintaan pasar.
                    </p>
                    <p>Apakah anda memiliki desain produk yang unik dan
                        membutuhkan perusahaan pihak ketiga untuk memasang
                        dan mewujudkannya untuk anda? Jika benar, maka anda
                        harus bekerjasama dengan perusahaan OEM untuk
                        mewujudkannya, sehingga anda akan melisensikan kepada
                        kami kemudian segala yang anda miliki pada cetak biru itu
                        dan produk jadi tersebut dapat dipasarkan dengan nama
                        merek dagang anda
                    </p>
                </div>
            </div>
        </div>
        <div class="row justify-content-center text-center">
            <div class="col-md-8 col-lg-12">
                <div class="title_sections">
                    <a href="<?= Url::toRoute(['/site/kontak-kami']) ?>" class="btn btn_md_primary margin-t-2 bg-green2 c-white sweep_top sweep_letter rounded-12">
                        <div class="inside_item">
                            <span data-hover="Buat Produk OEM">Buat Produk OEM</span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-lg-12">
                <div class="title_sections">
                    <h3>Free Jasa pembuatan Toko Online dengan sharing profit penjualan</h3>
                    <ul style="color: #6c7a87;">
                        <li>Hingga 100% Pembandingan yang Akurat</li>
                        <li>Memenuhi Kebutuhan dan Anggaran Anda</li>
                        <li>Stabilitas & Kompatibilitas Diuji</li>
                    </ul>
                </div>
            </div>

            <div class="col-md-8 col-lg-12">
                <div class="title_sections">
                    <!-- <div class="before_title">
                        <span class="c-green2">Integration</span>
                    </div> -->
                    <h3>Jasa pembuatan Toko Online tanpa sharing profit penjualan (beli putus)</h3>
                </div>
            </div>
        </div>
    </div>
</section>

_app/views/site/sertifikasi.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'Sertifikasi';

?>

<!-- Start banner_about -->
<section class="pt_banner_inner banner_px_image">
    <div class="parallax_cover">
        <img class="cover-parallax h-100vh" src="<?= Yii::$app->homeUrl ?>web/maklon/header.jpg" alt="">
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-6">
                <div class="banner_title_inner c-white">
                    <h1 data-aos="fade-up" data-aos-delay="0">
                        Sertifikasi
                    </h1>
                    <p data-aos="fade-up" data-aos-delay="100" class="banner_title_inner c-yollow">
                        Maklon Nutrisi & Beauty - PT Alga Rosan Nusantara
                    </p>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- End banner_about -->

<!-- Start Services -->
<section class="services_section padding-t-10">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-8 mb-4 mb-lg-0 margin-b-5">
                <div class="items_serv">
                    <div class="media">
                        <div>
                            <img src="<?= Yii::$app->homeUrl ?>web/maklon/sertifikat-gmp.png" alt="" style="width: 80%;"/>
                        </div>
                        <div class="media-body">
                            <h3>GMP</h3>
                            <p>Sistem produksi di perusahaan ini sudah tersertifikasi
                                dengan standar GMP atau yang disebut juga Good
                                Manufacturing Practice, sertifikasi ini menunjukkan
                                keamanan produksi yang pastinya telah terjaga dan ter
                                kontrol, sehingga kemanan produksi kosmetik anda dari
                                tahap formulasi hingga packaging serta pendistribusian
                                nya bisa terjamin keamanan dan konsistensinya.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-8 mb-4 mb-lg-0 margin-b-5">
                <div class="items_serv">
                    <div class="media">
                        <div>
                            <img src="<?= Yii::$app->homeUrl ?>web/maklon/sertifikat-ohsas.png" alt="" style="width: 80%;" />
                        </div>
                        <div class="media-body">
                            <h3>OHSAS</h3>
                            <p>OHSAS adalah sistem manajemen k3 standar internasional
                                untuk keselamatan kerja dan kesehatan, kepanjangan dari
                                OHSAS adalah Occupational Health and Safety Assesment
                                Series, jadi dengan adanya sertifikasi ini, kepastian
                                produksi bisa lebih terjaga dan keselamatan dalam
                                produksi bisa lebih maksimal, sehingga anda tidak perlu
                                khawatir untuk memproduksi kosmetik di perusahaan kami.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-8 mb-4 mb-lg-0 margin-b-5">
                <div class="items_serv">
                    <div class="media">
                        <div>
                            <img src="<?= Yii::$app->homeUrl ?>web/maklon/sertifikat-bpom.png" alt="" style="width: 80%;" />
                        </div>
                        <div class="media-body">
                            <h3>BPOM</h3>
                            <p>Semua produk kosmetik yang kami hasilkan pastinya
                                terdaftar dan tersertifikasi di BPOM, seperti yang kita
                                ketahui BPOM adalah lembaga yang mengawasi peredaran
                                produk makanan dan obat-obatan, termasuk kosmetik,
                                BPOM adalah singkatan dari Badan Pengawas Obat dan
                                Makanan, Jadi anda tidak perlu ragu, jika produk anda
                                sudah disetujui dan mendapat sertifikasi dari BPOM maka
                                produk anda sudah siap dijual di pasaran.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-8 mb-4 mb-lg-0 margin-b-5">
                <div class="items_serv">
                    <div class="media">
                        <div>
                            <img src="<?= Yii::$app->homeUrl ?>web/maklon/sertifikat-gmp.png" alt="" style="width: 80%;" />
                        </div>
                        <div class="media-body">
                            <h3>HACCP</h3>
                            <p>

                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-8 mb-4 mb-lg-0 margin-b-5">
                <div class="items_serv">
                    <div class="media">
                        <div>
                            <img src="<?= Yii::$app->homeUrl ?>web/maklon/sertifikat-mui.png" alt="" style="width: 80%;" />
                        </div>
                        <div class="media-body">
                            <h3>HALAL</h3>
                            <p>Sertifikasi Halal ini dikeluarkan oleh LPPOM MUI,
                                merupakan singkatan dari Lembaga Pengkajian Pangan,
                                Obat-Obatan, dan Kosmetika Majelis Ulama Indonesia,
                                sertifikasi ini menjamin ke-halalan produk mulai dari
                                formulasi, bahan baku, produksi, pengemasan, hingga
                                sampai di tangan konsumen, dengan adanya sertifikasi ini
                                membuat produk yang kami hasilkan sangat aman dan
                                halal untuk digunakan.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>